ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "panelWorkspaceTrialStartedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "panelWorkspaceDay5EmailSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "panelWorkspaceDay7ReminderSent" BOOLEAN NOT NULL DEFAULT false;
