import PDFDocument from "pdfkit";

export type MailPdfInput = {
  subject: string;
  from: string;
  to: string;
  date?: string;
  body: string;
  cc?: string;
  attachments?: string[];
};

function sanitizeFilename(subject: string): string {
  const base = subject.trim().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-").slice(0, 80);
  return `${base || "mail-trail"}.pdf`;
}

export function buildMailPdfFilename(subject: string): string {
  return sanitizeFilename(subject);
}

export async function generateMailPdf(input: MailPdfInput): Promise<{ buffer: Buffer; filename: string }> {
  const filename = sanitizeFilename(input.subject);

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).fillColor("#0f172a").text(input.subject || "Mail trail", { align: "left" });
    doc.moveDown(0.75);

    doc.fontSize(10).fillColor("#475569");
    doc.text(`From: ${input.from}`);
    doc.text(`To: ${input.to}`);
    if (input.cc?.trim()) doc.text(`Cc: ${input.cc}`);
    if (input.date?.trim()) doc.text(`Date: ${input.date}`);
    doc.moveDown(1);

    doc.strokeColor("#cbd5e1").moveTo(48, doc.y).lineTo(564, doc.y).stroke();
    doc.moveDown(0.75);

    doc.fontSize(11).fillColor("#0f172a").text(input.body || "(No message body)", {
      align: "left",
      lineGap: 4,
    });

    if (input.attachments?.length) {
      doc.moveDown(1);
      doc.fontSize(10).fillColor("#475569").text("Attachments:");
      for (const attachment of input.attachments) {
        doc.text(`• ${attachment}`);
      }
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor("#94a3b8").text("Generated by PMail+ Mail 2 PDF", { align: "right" });

    doc.end();
  });

  return { buffer, filename };
}
